#!/bin/bash

to_underline="Too yellow horse sang devilish songs."
line_char=-

underline_len="$(printf "%s" "$to_underline" | wc -m)"

# print
echo "$to_underline"
# underline
line_len="$underline_len" line_char="$line_char" interleaved=no bash draw-line bash draw_line
# make newline
echo
