#!/bin/bash

to_underline="Too yellow horse sang devilish songs."
line_char=-

underline_len="$(printf "%s" "$to_underline" | wc -m)"

# print
echo "$to_underline"
# underline
cat draw-line \
	| sed -e "s/\(line_len=\).*/\1$underline_len/" \
	| sed -e "s/\(line_char=\).*/\1$line_char/" \
	| sed -e "s/\(interleaved=\).*/\1no/" \
	| bash -s
# make newline
echo
