#!/bin/bash

# ARG_POSITIONAL_SINGLE([directory],[directory to list],[.])
# ARG_OPTIONAL_SINGLE([width],[w],[Width of the output])
# ARG_OPTIONAL_BOOLEAN([almost-all],[A],[Omit implicit '.' and '..' directories in the listing])
# ARG_HELP([Script that tells what 'ls' would do.])
# ARG_POSITIONAL_DOUBLEDASH()
# ARGBASH_GO()

# [

printf "Will list directory: "
printf "'%s', " "${_arg_directory}"
printf "\n"

if test -n "$_arg_width"
then
	printf "Padding the output to '%d' terminal columns.\n" "$_arg_width"
fi

test "$_arg_almost_all" = on && echo "Omitting implicit '.' and '..' directories in the listing."

# ]
